window.ROOT = '/app';
var URL = {
    GET_USER_INFO : "/Yishang/user/detail",
    SOLUTION_LIST : "/Yishang/solution/list",
    CREATE_SCHEME : "/Yishang/solution/insert",
    UPDATE_SCHEME : "/Yishang/solution/update",
    MODULE_LIST : "/Yishang/module/list",
    CREATE_MODULE : "/Yishang/module/insert",
    UPDATE_MODULE : "/Yishang/module/update",
    COMPONENT_LIST : "/Yishang/component/inst/selectInstCpts",
    CREATE_CPTINST : "/Yishang/cptInst/add",
    DELETE_CPTINT : "/Yishang/component/inst/delete",
    GET_CPTINST_ATTR : "/Yishang/cptInst/getAttr",
    UPDATE_CPTiNST_ATTR : "/Yishang/cptInst/update",
    UPDATE_GET_DATA : "/Yishang/cptInst/updateAndGetData",
    GET_CPTINST_DATA : "/Yishang/cptInst/getData",
    GET_REL_CPT : "/Yishang/baseCpt/getRelCpt",
    GET_COMPONENT_BASE_LIST : "/Yishang/component/base/list",
    GET_COMPONENT_BASE_DETAIL : "/Yishang/component/base/detail",
    GET_STYLE_LIST : "/Yishang/baseCpt/getStyList",
    GET_PHONE_LIST : "/Yishang/component/data/selectBrandModelList",
    GET_SOURCE_DATA : "/Yishang/config/selectNetInfoSource",
    GET_INST_ATTR_GROUP : "/Yishang/component/inst/groupAttr",
    UPDATE_SYNC_TYPE : "/Yishang/cptInst/updateSyncType"
};